ARG MET_BASE_REPO=registry1.dso.mil/ironbank/opensource/debian/debian
ARG MET_BASE_TAG=12-slim
FROM ${MET_BASE_REPO}:${MET_BASE_TAG}
LABEL maintainer="John Halley Gotway <johnhg@ucar.edu>"

#
# Constants
# Original Tomcat Source:
#   https://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_MAJOR_VERSION}/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz
#
ENV TOMCAT_MAJOR_VERSION=10
ENV TOMCAT_MINOR_VERSION=1.48
ENV TOMCAT_VERSION=${TOMCAT_MAJOR_VERSION}.${TOMCAT_MINOR_VERSION}
ENV TOMCAT_URL=https://dtcenter.ucar.edu/dfiles/code/METplus/MET/docker_data/apache-tomcat-${TOMCAT_VERSION}.tar.gz
ENV CATALINA_HOME=/opt/tomcat

# Expose METviewer port
EXPOSE 8080

ENV PYTHON_VER=3.12.11

# - install build-essential, libffi-dev, and libssl-dev for Pip SSL support

RUN \
     echo "Install system updates" &&\
     apt -y update && apt -y upgrade \
  && echo "Install required packages" &&\
     apt -y install ant build-essential libffi-dev libssl-dev ksh mariadb-server openjdk-17-jdk r-base wget &&\
     apt clean \
  && echo "Setup default cran repo" &&\
     echo "r <- getOption('repos'); r['CRAN'] <- 'http://cran.us.r-project.org'; options(repos = r);" > ~/.Rprofile \
  && echo "Install required R packages" &&\
     Rscript -e "install.packages('boot')" &&\
     Rscript -e "install.packages('plotrix')" &&\
     Rscript -e "install.packages('gsl')" &&\
     Rscript -e "install.packages('data.table')" &&\
     Rscript -e "install.packages('verification')" \
  && echo "Install Tomcat" &&\
     wget ${TOMCAT_URL} &&\
     tar -xvf apache-tomcat-${TOMCAT_VERSION}.tar.gz &&\
     rm apache-tomcat*.tar.gz &&\
     mv apache-tomcat* ${CATALINA_HOME} &&\
     chmod +x ${CATALINA_HOME}/bin/*sh \
 && echo "Install Python from source" &&\
    wget https://www.python.org/ftp/python/${PYTHON_VER}/Python-${PYTHON_VER}.tgz &&\
    tar xzf Python-${PYTHON_VER}.tgz &&\
    (cd Python-${PYTHON_VER} &&\
    ./configure --enable-optimizations --enable-shared --disable-test-modules \
      LDFLAGS="-L/usr/local/lib -Wl,-rpath,/usr/local/lib" &&\
    make -j `nproc` &&\
    make install) &&\
    ln -s /usr/local/bin/python3 /usr/local/bin/python &&\
    rm -rf Python-${PYTHON_VER}* \
  && echo "Create a link for python3" &&\
     ln -sf /usr/local/bin/python3  /usr/bin/python3 &&\
     ln -sf /usr/bin/python3  /usr/bin/python &&\
     ln -sf /usr/local/bin/pip3  /usr/bin/pip3 &&\
     ln -sf /usr/bin/pip3  /usr/bin/pip

WORKDIR /tmp

#
# - Install Python packages needed for METplus Analysis Python tools
#

RUN echo "Install GEOS - needed for cartopy" &&\
    wget http://download.osgeo.org/geos/geos-3.7.2.tar.bz2 && tar xjf geos-3.7.2.tar.bz2 &&\
    (cd geos-3.7.2 && ./configure && make clean && make && make install && ldconfig) &&\
     rm -r geos-3.7.2.tar.bz2 \
  && echo "Install Python packages" \
  && pip install PyMySQL\
      attrs \
      cartopy \
      eofs \
      exceptiongroup \
      imageio \
      imutils \
      iniconfig \
      kaleido \
      lxml \
      matplotlib \
      metpy \
      netCDF4 \
      numpy \
      opencv-python \
      packaging \
      pandas \
      pint \
      plotly \
      pluggy \
      pytest \
      python-dateutil \
      pytz \
      pyyaml \
      scikit-image \
      scikit-learn \
      scipy \
      setuptools \
      six \
      tomli \
      wheel \
      xarray \
  && echo "Install chrome for plotly/kaleido" &&\
     wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb &&\
     apt-get install -y ./google-chrome-stable_current_amd64.deb \
  && apt clean
