ARG MET_BASE_TAG
FROM dtcenter/met-base:${MET_BASE_TAG}
LABEL maintainer="John Halley Gotway <johnhg@ucar.edu>"

#
# Set the working directory.
#
WORKDIR /met

#
# Download and install MET and GhostScript fonts.
# Delete the MET source code for tagged releases matching "v"*.
#
RUN echo "Installing tools needed for running MET unit tests..." \
 && echo "Installing Perl XML Parser..." \
 && apt update && apt -y upgrade \
 && apt install -y libxml-parser-perl \
 && echo "Installing R..." \
 && apt install -y r-base \
 && echo "Installing R ncdf4 1.21..." \
 && wget https://cran.r-project.org/src/contrib/Archive/ncdf4/ncdf4_1.21.tar.gz \
 && R CMD INSTALL --configure-args="--with-nc-config=/usr/local/netcdf/netcdf-c-4.7.4/nc-config" ncdf4_1.21.tar.gz \
 && echo "Installing NCO and netcdf-bin (for ncdiff)..." \
 && apt install -y nco netcdf-bin \
 && apt clean \
 && echo "Finished installing unit test tools"
