ARG MET_BASE_REPO
ARG MET_BASE_TAG
FROM ${MET_BASE_REPO}:${MET_BASE_TAG}

LABEL maintainer="George McCabe <mccabe@ucar.edu>"

# Set the working directory.

WORKDIR /met

ENV NCO_URL=https://dtcenter.ucar.edu/dfiles/code/METplus/MET/docker_data/nco-5.3.3.tar.gz

# - Install Perl XML parser, R (with ncdf4) and NC tools
# - Install nco 5.3.3 from source to avoid CVEs in HDF5 1.10.8 packages

RUN echo "Installing tools needed for running MET unit tests..." \
 && echo "Installing Perl XML Parser..." &&\
    dnf install -y perl-XML-Parser \
 && echo "Installing R..." \
    dnf install -y xdg-utils flexiblas-devel libtirpc-devel &&\
    dnf install -y R-core R-core-devel &&\
    dnf clean all \
 && echo "Installing R ncdf4..." &&\
    echo "r <- getOption('repos'); r['CRAN'] <- 'http://cran.us.r-project.org'; options(repos = r);" > ~/.Rprofile &&\
    Rscript -e "install.packages('ncdf4', configure.args='--with-nc-config=/usr/local/bin/nc-config')" \
 && echo "Installing udunits..." &&\
    dnf install -y udunits2-devel &&\
    echo "Downloading nco from ${NCO_URL}" \
 && wget ${NCO_URL} && tar xzf nco-5.3.3.tar.gz &&\
    (cd nco-5.3.3 &&\
     ./configure --enable-shared CPPFLAGS="-I/usr/include/udunits2" &&\
     make -j $(nproc) && make install) \
 && echo "Finished installing unit test tools"
