ARG BASE_REGISTRY=docker.io
ARG BASE_IMAGE=redhat/ubi9
ARG BASE_TAG=9.7
FROM ${BASE_REGISTRY}/${BASE_IMAGE}:${BASE_TAG}

LABEL maintainer="George McCabe <mccabe@ucar.edu>"

#
# Constants
# Original Tomcat Source:
#   https://archive.apache.org/dist/tomcat/tomcat-${TOMCAT_MAJOR_VERSION}/v${TOMCAT_VERSION}/bin/apache-tomcat-${TOMCAT_VERSION}.tar.gz
#
ENV TOMCAT_MAJOR_VERSION=10
ENV TOMCAT_MINOR_VERSION=1.55
ENV TOMCAT_VERSION=${TOMCAT_MAJOR_VERSION}.${TOMCAT_MINOR_VERSION}
ENV TOMCAT_URL=https://dtcenter.ucar.edu/dfiles/code/METplus/MET/docker_data/apache-tomcat-${TOMCAT_VERSION}.tar.gz
ENV CATALINA_HOME=/opt/tomcat

# Expose METviewer port
EXPOSE 8080

ENV PYTHON_VER=3.14.4

WORKDIR /tmp

# - install build-essential, libffi-dev, and libssl-dev for Pip SSL support
# - Install Python packages needed for METplus Analysis Python tools

#     apt -y install ant build-essential ghostscript git libffi-dev libssl-dev ksh \
#                    mariadb-server openjdk-17-jdk r-base wget &&\

RUN \
     echo "Upgrade system packages" &&\
     dnf upgrade -y --refresh --nodocs \
  && echo "Install required packages" &&\
     rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9 &&\
     dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm &&\
     /usr/bin/crb enable &&\
     echo -e "[centos-baseos]\n\
name=CentOS Stream 9 - BaseOS\n\
baseurl=https://mirror.stream.centos.org/9-stream/BaseOS/x86_64/os/\n\
gpgcheck=0\n\
enabled=1\n\
\n\
[centos-appstream]\n\
name=CentOS Stream 9 - AppStream\n\
baseurl=https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/\n\
gpgcheck=0\n\
enabled=1\n\
\n\
[centos-crb]\n\
name=CentOS Stream 9 - CRB\n\
baseurl=https://mirror.stream.centos.org/9-stream/CRB/x86_64/os/\n\
gpgcheck=0\n\
enabled=1" > /etc/yum.repos.d/centos.repo &&\
     dnf clean all && dnf makecache &&\
     dnf install -y --nodocs ant bzip2 git gsl gsl-devel \
       java-17-openjdk-headless libffi-devel mariadb-server openssl-devel &&\
     dnf install -y xdg-utils flexiblas-devel libtirpc-devel &&\
     dnf install -y R-core R-core-devel &&\
     dnf clean all \
  && echo "Setup default cran repo" &&\
     echo "r <- getOption('repos'); r['CRAN'] <- 'http://cran.us.r-project.org'; options(repos = r);" > ~/.Rprofile \
  && echo "Install required R packages" &&\
     Rscript -e "install.packages('boot')" &&\
     Rscript -e "install.packages('plotrix')" &&\
     Rscript -e "install.packages('gsl')" &&\
     Rscript -e "install.packages('data.table')" &&\
     Rscript -e "install.packages('verification')" \
  && echo "Install Tomcat" &&\
     curl -O ${TOMCAT_URL} &&\
     tar -xvf apache-tomcat-${TOMCAT_VERSION}.tar.gz &&\
     rm apache-tomcat*.tar.gz &&\
     mv apache-tomcat* ${CATALINA_HOME} &&\
     chmod +x ${CATALINA_HOME}/bin/*sh \
 && echo "Install Python from source" &&\
    curl -O https://www.python.org/ftp/python/${PYTHON_VER}/Python-${PYTHON_VER}.tgz &&\
    tar xzf Python-${PYTHON_VER}.tgz &&\
    (cd Python-${PYTHON_VER} &&\
    ./configure --enable-optimizations --enable-shared --disable-test-modules \
      LDFLAGS="-L/usr/local/lib -Wl,-rpath,/usr/local/lib" &&\
    make -j `nproc` &&\
    make install) &&\
    ln -s /usr/local/bin/python3 /usr/local/bin/python &&\
    rm -rf Python-${PYTHON_VER}* \
  && echo "Create a link for python3" &&\
     ln -sf /usr/local/bin/python3  /usr/bin/python3 &&\
     ln -sf /usr/bin/python3  /usr/bin/python &&\
     ln -sf /usr/local/bin/pip3  /usr/bin/pip3 &&\
     ln -sf /usr/bin/pip3  /usr/bin/pip \
  && echo "Install GEOS - needed for cartopy" &&\
     curl -O http://download.osgeo.org/geos/geos-3.7.2.tar.bz2 && tar xjf geos-3.7.2.tar.bz2 &&\
     (cd geos-3.7.2 && ./configure && make clean && make && make install && ldconfig) &&\
     rm -r geos-3.7.2.tar.bz2 \
  && echo "Install Python packages" &&\
     pip install --upgrade pip &&\
     pip install PyMySQL\
      cartopy \
      eofs \
      imageio \
      imutils \
      lxml \
      matplotlib \
      metpy \
      netCDF4 \
      pandas \
      pytest \
      pyyaml \
      scipy \
      xarray
