name: Build Docker Images

on:
  push:
    branches:
      - develop
    tags:
      - v*

  workflow_dispatch:

env:
  DOCKERHUB_BASE_REPO: dtcenter/met-base
  DOCKERHUB_UNIT_TEST_REPO: dtcenter/met-base-unit-test
  DOCKERHUB_METVIEWER_REPO: dtcenter/met-base-metviewer

jobs:

  handle_docker_images:
    name: Handle Docker Images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: .github/jobs/build_docker_image.sh
        env:
          GITHUB_NAME: ${{ github.ref_name }}

      - name: Push Docker Image
        run: .github/jobs/push_docker_image.sh
        env:
          GITHUB_NAME: ${{ github.ref_name }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


