name: Pull and Scan Docker image

on:

  workflow_dispatch:
    inputs:
      image_name:
        description: 'Image to pull and scan e.g. dtcenter/met-base-dev:develop'
        default: 'dtcenter/met-base-dev:develop'
        required: true
        type: string

jobs:

  pull_and_scan:
    name: Pull and Scan Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Pull Docker Image
        run: docker pull ${{ inputs.image_name }}

      - name: Scan Docker Images
        uses: dtcenter/metplus-action-scan-docker-images@v1
        with:
          images: |
            [
              "${{ inputs.image_name }}"
            ]
          fail-on-critical: "true"
