name: Pull and Scan Docker image

on:

  workflow_dispatch:
    inputs:
      image_name:
        description: 'Image to pull and scan e.g. dtcenter/met-base-dev:develop'
        default: 'dtcenter/met-base-dev:develop'
        required: true
        type: string

jobs:

  pull_and_scan:
    name: Pull and Scan Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create directories to store output
        run: |
          mkdir -p ${RUNNER_WORKSPACE}/logs

      - name: Pull Docker Image
        run: |
          docker pull ${{ inputs.image_name }}

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan Docker Image
        run: .github/jobs/scan_single_docker_image.sh ${{ inputs.image_name }}

      - name: Upload logs as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs_cve_scan 
          path: ${{ runner.workspace }}/logs
          if-no-files-found: ignore

